apiVersion: apps/v1
kind: Deployment
metadata:
  name: iotservice01
spec:
  replicas: 1
  selector:
    matchLabels:
      app: iotservice01
  template:
    metadata:
      name: iotservice01
      labels:
        app: iotservice01
        area: zone1
        qos_latency: "40"
        qos_bandwidth: "1000"
        device_ip : "192.168.4.1"
        strategies : migration, firmware, reconfiguration
        firmware : ota, reset
        reconfiguration :
          FRAMESIZE_QQVGA : 250
          FRAMESIZE_HQVGA : 400
          FRAMESIZE_QVGA : 700
          FRAMESIZE_CIF: 800
          FRAMESIZE_VGA : 900
          FRAMESIZE_SVGA : 1000
          FRAMESIZE_UXGA : 1100

    spec:
      containers:
        - name: iotservice1pod1-container
          image: tempdecal/odmv3:2.8.0
          imagePullPolicy: IfNotPresent
          resources:
            limits:
              memory: "512Mi"
            requests:
              memory: "512Mi"
          command:
            - /sbin/init
      schedulerName: custom-scheduler
