apiVersion: apps/v1
kind: Deployment
metadata:
  name: iotservice01
spec:
  replicas: 1
  selector:
    matchLabels:
      app: iot_service_01
  template:
    metadata:
      name: iotservice01
      labels:
        app: iot_service_01
        area: zone1
        qos_latency: "18"
    spec:
      containers:
        - name: iotservice1pod1-container
          image: tempdecal/odmv3:2.6.0
          imagePullPolicy: Never
          resources:
            limits:
              memory: "1Gi"
            requests:
              memory: "1Gi"
          command:
            - /sbin/init
      schedulerName: custom-scheduler
