apiVersion: apps/v1
kind: Deployment
metadata:
  name: iotservice01
spec:
  replicas: 1
  selector:
    matchLabels:
      app: iotservice01
  template:
    metadata:
      name: iotservice01
      labels:
        app: iotservice01
        area: zone1
        qos_latency: "100"
        qos_bandwidth: "10"
        device_ip : "192.168.4.1"
    spec:
      containers:
        - name: iotservice1pod1-container
          image: tempdecal/odmv3:2.8.0
          imagePullPolicy: IfNotPresent
          resources:
            limits:
              memory: "512Mi"
            requests:
              memory: "512Mi"
          command:
            - /sbin/init
      schedulerName: custom-scheduler
