apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment4
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app4
  template:
    metadata:
      name: pod4
      labels:
        delay_deployment3: "1"
        app: app4
    spec:
      containers:
      - name: pod4-container
        image: docker.io/centos/tools:latest
        resources:
          limits:
            memory: "1Gi"
          requests:
            memory: "1Gi"
        command:
        - /sbin/init
      schedulerName: custom-scheduler
